version: '3.8'

services:
  frontend:
    build:
      context: .
      target: frontend-builder
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    command: npm run dev
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000

  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000 