name: Docker CI/CD

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 20

    steps:
      - name: Configure Git
        run: |
          git config --global --add safe.directory "*"
        shell: bash

      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Stop and Remove Old Container
        shell: bash
        continue-on-error: true
        run: |
          docker stop fms-container || echo "Container not running"
          docker rm fms-container || echo "Container not found"
          docker images fms-container -q | xargs -r docker rmi || echo "Image not found"
          docker images --filter "dangling=true" -q | xargs -r docker rmi || echo "No dangling images"

      - name: Build Docker image
        shell: bash
        run: |
          docker build \
          --no-cache \
          -t fms-container:latest \
          .

      - name: Run Docker container
        shell: bash
        run: |
          docker run -d \
          --name fms-container \
          -p 8055:8055 \
          --restart unless-stopped \
          fms-container:latest

      - name: Check container health
        shell: bash
        run: |
          sleep 30
          docker ps | grep "fms-container" || exit 1
          docker logs fms-container --tail 50

